# Docker entry point for this project.
# MySQL and Wordpress
# Author Tony Garand

version: "3.7"

services: 
  #Database
  db:
    image: mysql/mysql-server:latest
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3306:3306"
    volumes:
      - ~/src/mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      
  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html
    volumes:
      - ./frontend:/var/www/html/wp-content
      - ./backend:/var/www/html/

volumes:
  db_data:
      
